name: 'Deploy lambda function: trames_api' #Name of the Workflow

env:
  function_folder: my_lambda_function
  lambda_function_ARN: arn:aws:lambda:ap-southeast-1:484750731673:function:sl-de_tramesAPI

## Define CD for lambda function on pushing into main.
on:
  # push:
  #   branches:
  #     - 'master'

  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

  workflow_dispatch:

#### End On

jobs:  #Workflow run is made up of one or more jobs
  deploy_lambda_function:
    runs-on: ubuntu-latest  #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v2  # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:  
          node-version: '14' #--> Specify the Version of the Node 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 #--> Define Region of the AWS-CLI 

      - name: deploy_lambda
        run: |
          cd $function_folder; zip -r ../deploy.zip *; cd .. #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=$lambda_function_ARN --zip-file=fileb://deploy.zip 
# At last the AWS CLI command to Update the Zip file with existing One (With Correct Function Name)